spring:
  datasource:
    url: jdbc:h2:mem:hoteldb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: Hotel_API

server:
  port: 8092
